'use strict';
const crypto=require('crypto');
const {getPool,transaction}=require('../db/connection');
const ACCESS_TTL_MS=Number(process.env.ACCESS_TOKEN_TTL_MS||15*60*1000);
const REFRESH_TTL_MS=Number(process.env.REFRESH_TOKEN_TTL_MS||30*24*60*60*1000);
const token=()=>crypto.randomBytes(48).toString('base64url');
const hash=t=>crypto.createHash('sha256').update(String(t)).digest('hex');
async function createSession({userId,deviceId=null,userAgent=null,ip=null}){const access=token(),refresh=token(),now=Date.now(),p=getPool();if(!p)throw new Error('Postgres is required for production sessions');const r=await p.query(`INSERT INTO auth_sessions(user_id,access_token_hash,refresh_token_hash,device_id,user_agent,ip_hash,access_expires_at,refresh_expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING session_id`,[userId,hash(access),hash(refresh),deviceId,userAgent,ip?hash(ip):null,new Date(now+ACCESS_TTL_MS),new Date(now+REFRESH_TTL_MS)]);return {sessionId:r.rows[0].session_id,accessToken:access,refreshToken:refresh,accessExpiresAt:new Date(now+ACCESS_TTL_MS).toISOString(),refreshExpiresAt:new Date(now+REFRESH_TTL_MS).toISOString()};}
async function rotate(refreshToken,{deviceId=null,userAgent=null,ip=null}={}){if(!refreshToken||!getPool())return null;return transaction(async c=>{const q=await c.query(`SELECT * FROM auth_sessions WHERE refresh_token_hash=$1 AND revoked_at IS NULL AND refresh_expires_at>now() FOR UPDATE`,[hash(refreshToken)]);if(!q.rowCount)return null;const old=q.rows[0],access=token(),refresh=token(),now=Date.now();const n=await c.query(`INSERT INTO auth_sessions(user_id,access_token_hash,refresh_token_hash,device_id,user_agent,ip_hash,access_expires_at,refresh_expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING session_id`,[old.user_id,hash(access),hash(refresh),deviceId||old.device_id,userAgent||old.user_agent,ip?hash(ip):old.ip_hash,new Date(now+ACCESS_TTL_MS),new Date(now+REFRESH_TTL_MS)]);await c.query(`UPDATE auth_sessions SET revoked_at=now(),replaced_by=$2,last_seen_at=now() WHERE session_id=$1`,[old.session_id,n.rows[0].session_id]);return {sessionId:n.rows[0].session_id,userId:old.user_id,accessToken:access,refreshToken:refresh,accessExpiresAt:new Date(now+ACCESS_TTL_MS).toISOString(),refreshExpiresAt:new Date(now+REFRESH_TTL_MS).toISOString()};});}
async function validate(accessToken){if(!accessToken||!getPool())return null;const r=await getPool().query(`SELECT session_id,user_id,device_id FROM auth_sessions WHERE access_token_hash=$1 AND revoked_at IS NULL AND access_expires_at>now()`,[hash(accessToken)]);if(!r.rowCount)return null;await getPool().query('UPDATE auth_sessions SET last_seen_at=now() WHERE session_id=$1',[r.rows[0].session_id]);return r.rows[0];}
async function revoke(accessToken){if(accessToken&&getPool())await getPool().query('UPDATE auth_sessions SET revoked_at=COALESCE(revoked_at,now()) WHERE access_token_hash=$1',[hash(accessToken)]);}
async function revokeRefresh(refreshToken){if(refreshToken&&getPool())await getPool().query('UPDATE auth_sessions SET revoked_at=COALESCE(revoked_at,now()) WHERE refresh_token_hash=$1',[hash(refreshToken)]);}
async function revokeUser(userId){if(getPool())await getPool().query('UPDATE auth_sessions SET revoked_at=COALESCE(revoked_at,now()) WHERE user_id=$1 AND revoked_at IS NULL',[userId]);}
module.exports={createSession,rotate,validate,revoke,revokeUser,revokeRefresh,ACCESS_TTL_MS,REFRESH_TTL_MS};
